### ISSUE TITLE
TypeError: data.map is not a function in QuestionList.tsx

### ISSUE THREAD

**Issue by ajs424** [PacktPublishing/ASP.NET-Core-3-and-React#20]
```
import React from 'react';
import { FC } from 'react';

import { QuestionData } from './QuestionsData';
import { Question } from './Question';
import './Styles/QuestionList.scss';

interface Props {
  data: QuestionData[];
  renderItem?: (item: QuestionData) => JSX.Element;
}

export const QuestionList: FC<Props> = ({ data, renderItem }) => {
  return (
    <ul>
      {data.map((question) => (
        <li key={question.questionId}>
          {renderItem ? renderItem(question) : <Question data={question} />}
        </li>
      ))}
    </ul>
  );
};
```

code (without emotion) in QuestionList throws a TypeError.

**Comment by carlrip** [comment]
I'm struggling to recreate this error ...

I built a CodeSandbox with your QuestionList component and it seems to works okay.
[https://codesandbox.io/s/sparkling-sound-icnql](https://codesandbox.io/s/sparkling-sound-icnql)

I think the problem might be in the code that is consuming the QuestionList component. The `data` prop that is passed in must be an array of `QuestionData`.
