### ISSUE TITLE
Form validation chapter - why not just use browser's native validation? 

### ISSUE THREAD

**Issue by MaTToX3** [PacktPublishing/ASP.NET-Core-3-and-React#21]
Currently working on a book - it's great! However I am having difficulties understanding the whole validation chaptepter - why go all trough this in a way it's done in a book? Why not use a input attributes (required, min, max, minlength, maxlength, ...) for something so trivial? Seems like a lot of code for a client-side validation. Any specific reasons why it is done the way it is done?

Thanks in advance!

**Comment by carlrip** [comment]
Thanks for the question!

You can certainly use the standard clientside validation for simple use cases. A common reason why these won't be used, is to have control over on UX for the validation error. You can't style the standard error message and it is different in each browser. Also, you can't declare when the validation triggers (i.e. when the field is changed, loses focus, or when the form is submitted). Also, these validation rules can only be applied on a certain set of native elements - we might want to apply validation on a React component.

Hope this helps.

**Comment by MaTToX3** [comment]
Thank you for your reply!
